// Automagically generated by enummaker.exe.
// DO NOT EDIT THIS FILE (Yes, I mean you!)
#ifndef __glbdef_h__
#define __glbdef_h__

#include "mygba.h"
#include "rand.h"

// Definitions for ITEM
enum ITEM_NAMES
{
    ITEM_MUSHROOM,
    NUM_ITEMS
};

struct ITEM_DEF
{
    const char *name;
    u8 symbol;
    u8 attr;
};

extern const ITEM_DEF glb_itemdefs[];

// Definitions for MOB
enum MOB_NAMES
{
    MOB_NONE,
    MOB_TIMMY,
    MOB_SMITH,
    MOB_MRSSMITH,
    MOB_FARMERJOE,
    MOB_FARMERAMY,
    MOB_ELDER,
    MOB_BAKER,
    MOB_MRSBAKER,
    MOB_RAT,
    MOB_BAT,
    MOB_ZOMBIE,
    MOB_SKELETON,
    MOB_KOBOLD,
    MOB_SKELETONCAPTAIN,
    MOB_LARGEZOMBIE,
    MOB_GHOST,
    MOB_TLOSH,
    MOB_ZOMBIETIMMY,
    NUM_MOBS
};

struct MOB_DEF
{
    u8 symbol;
    u8 attr;
    const char *name;
    bool isfriendly;
    const char *melee_name;
    const char *melee_verb;
    u8 melee_damage;
    const char *range_name;
    const char *range_verb;
    u8 range_damage;
    u8 range_range;
    u8 range_symbol;
    u8 range_attr;
    u8 max_hp;
    u8 depth;
    u8 ai;
    bool isslow;
    bool isfast;
    bool quest_shroom;
    bool quest_timmy;
};

extern const MOB_DEF glb_mobdefs[];

// Definitions for AI
enum AI_NAMES
{
    AI_NONE,
    AI_HOME,
    AI_CHARGE,
    AI_FLANK,
    AI_RANGE,
    NUM_AIS
};

// Definitions for TILE
enum TILE_NAMES
{
    TILE_INVALID,
    TILE_FLOOR,
    TILE_DOWNSTAIRS,
    TILE_UPSTAIRS,
    TILE_SNOWYPATH,
    TILE_PATH,
    TILE_GRASS,
    TILE_FIELD,
    TILE_FIRE,
    TILE_WALL,
    TILE_DOOR,
    TILE_MOUNTAIN,
    TILE_ICEMOUNTAIN,
    TILE_SNOWYPASS,
    TILE_BRIDGE,
    TILE_WATER,
    TILE_FOREST,
    NUM_TILES
};

struct TILE_DEF
{
    u8 symbol;
    u8 attr;
    const char *legend;
    bool ispassable;
    bool istransparent;
};

extern const TILE_DEF glb_tiledefs[];

// Definitions for ATTR
enum ATTR_NAMES
{
    ATTR_BORDER,
    ATTR_HILITE,
    ATTR_ELECTRICBLUE,
    ATTR_METAL,
    ATTR_YELLOW,
    ATTR_PURPLE,
    ATTR_NORMAL,
    ATTR_LIGHTBLACK,
    ATTR_OUTOFFOV,
    ATTR_WHITE,
    ATTR_ORANGE,
    ATTR_BROWN,
    ATTR_GREEN,
    ATTR_DKGREEN,
    ATTR_BLUE,
    NUM_ATTRS
};

struct ATTR_DEF
{
    u8 bg_r;
    u8 bg_g;
    u8 bg_b;
    u8 fg_r;
    u8 fg_g;
    u8 fg_b;
};

extern const ATTR_DEF glb_attrdefs[];
#endif
